### ISSUE TITLE
RadioButtonList EditorTemplate

### ISSUE THREAD

**Issue by jasonhjohnson** [JaroslawWaliszko/ExpressiveAnnotations#45]
Hi,

I have a custom RadioButtonList editor template that I use like:

[UIHint("RadioButtonList")]
public string MyProperty { get; set;}

....

It doesn't seem like I'm able to use the client-side expresssive annotations in this case. When I move the code out of the editor template and into the calling Razor view everything works fine. Maybe I'm missing something?

Any help is appreciated.

Thanks,
Jason

**Comment by JaroslawWaliszko** [comment]
Hi,

Provide some more comprehensive code samples of your model, view and the RadioButtonList template itself. I'll try to debug through it and possibly figure out where is the problem.

Regards

**Comment by jasonhjohnson** [comment]
Thanks!

Here is a link to the Gist with relevant code:
https://gist.github.com/jasonhjohnson/19c53cf19a10e434d46d

Best,
Jason

On Mon, Jan 26, 2015 at 4:26 PM, Jaroslaw Waliszko <notifications@github.com

**Comment by jasonhjohnson** [comment]
Also, I haven't been able to get the client-side portion working with
RequireJS. I'm not sure if it's AMD-compatible? Also, does
DataAnnotationsModelValidatorProvider.RegisterAdapter(typeof(RequiredIfAttribute),
typeof(RequiredIfValidator));

DataAnnotationsModelValidatorProvider.RegisterAdapter(typeof(AssertThatAttribute),
typeof(AssertThatValidator)) look for the expressive-annotations.js in a
specific folder/location?

-J

**Comment by jasonhjohnson** [comment]
Also,

Is there a way to require the user to check a checkbox IF another field is
set to a specific value?

Example:

[Display(Name = "I'm checking this box to confirm my electronic signature
and acceptance.")]
[RequiredIf("RenewalFormGroupStatusId == 3")]
[AssertThat("RenewalFormGroupStatusId != 3 && (AuthorizedAcceptance !=
true)", ErrorMessage = "You must authorize before saving as complete.")]

public bool AuthorizedAcceptance { get; set; }

Does that make sense?

Thanks,
Jason

**Comment by JaroslawWaliszko** [comment]
Answering your last question, it should look like below:
```
[RequiredIf("RenewalFormGroupStatusId == 3")] // when something is required it means non-null
[AssertThat("AuthorizedAcceptance  == true)", ErrorMessage = "You must authorize...")]
public bool? AuthorizedAcceptance { get; set; } // see nullable bool
```
Regarding the first one - just by looking at gist sample you've sent, I see that the `input` element of your custom radio button construction suffers from lack of attributes, essential for client-side validation to work. They are automatically added when using MVC provided helpers though. Just compare output html of your version with the one generated by standard way of doing it - when using `RadioButtonFor` helper there is additional stuff automatically generated:
```
<input 
    data-val="true" 
    data-val-requiredif="Please provide an answer before completing the application." 
    data-val-requiredif-allowempty="false" 
    data-val-requiredif-constsmap="{}" 
    data-val-requiredif-expression="GoAbroad" 
    data-val-requiredif-fieldsmap="{&quot;GoAbroad&quot;:&quot;bool&quot;}" 
```
Answering the second question - validators. Validators registered in Global.asax are needed for client validation rules generation. Based on the expressions parser output, rules (`constsmap`, `fieldsmap` etc) are created and sent to client, then used to build your html fields automatically if using MVC helpers (e.g. radio helper in your case). They have nothing in common with the script file - they just prepare some information that script (when loaded in the page) is going to eventually use.

Finally, I've not used nor tested that with the RequireJS so I'm not able to provide any hints related to that case (at least not right now).

**Comment by jasonhjohnson** [comment]
Thank you very much for all of this. I've got most everything working.

The last issue I'm having is that the client-side validation for expressive
annotations only appears to happen SOME times. It's strange and I can't
figure it out. Can you think of any reason why this would be the case?

Thanks,
Jason

On Wed, Jan 28, 2015 at 6:47 PM, Jaroslaw Waliszko <notifications@github.com

**Comment by JaroslawWaliszko** [comment]
Just to update my last answer. I've actually noticed that you were referring to a checkbox in your last question. I've given an answer with nullable bool, which can be applicable to radios instead. If you get it working I assume you figured out that but I'll just supplement my answer. 

So, when dealing with checkbox, there are only 2 states: checked (`true`) or unchecked (`false`) - value is always there, there is no `null` state. In that case the answer should be:
```
[AssertThat("!AuthorizedAcceptance || (AuthorizedAcceptance && RenewalFormGroupStatusId==3))")]
public bool AuthorizedAcceptance { get; set; }
```
As you can see nullable is removed and because of that `RequiredIf` attribute is also removed. It does make no sense for applying `RequiredIf` attribute to non-nullable fields, because the value is always there - in an unchecked checkbox it is just `false`.

So the assertion is enough because it will be fired no matter in which state checkbox is. The assertion says that: field can be just `false` (unchecked) in one case, or  when some other field has certain value (3 in this case) - `true` (checked). Assertion just needs to be satisfied, otherwise error will be shown, so put there anything that makes sense to you.

Referring to your latest question, the description is too broad. These "some" times are for sure different in some cases from the "other" times. Maybe you're referring to dependency validations? Some fields are re-validated by default when the fields on which they depend on are changed. Mabye this revalidation is confusing to you - it can be turned off: `dependencyTriggers: undefined` so validation will be triggered only when submit button is pressed.

Finally, if there is only client-side issue you can just check out firebug/chrome/ie console for any errors on printed to console output or possibly just debug through the script code - the starting breakpoints can be:

![image](https://cloud.githubusercontent.com/assets/1596462/5960634/38b81bd4-a7d7-11e4-8c4a-fa63cb2dc2b6.png)

**Comment by jasonhjohnson** [comment]
Jaroslaw I can't thank you enough for your detailed responses. It's very
insightful.

I actually removed the RequiredIf and wrote the Assert as follows:
[AssertThat("RenewalFormGroupStatusId == 3 && AuthorizedAcceptance == true
|| RenewalFormGroupStatusId != 3", ErrorMessage = "You must authorize
before saving as complete.")]

I'll update the AssertThat with your version.

Regarding the client-side SOMETIMES working issue:

I added the following code which seems to have fixed it:
refreshValidator: function () {
            // This ensures that our unobtrusive and expressive annotations
are applied
            // to the current/primary form being worked with
            var $form = $('#primary-form');
            $form.removeData("validator");
            $form.removeData("unobtrusiveValidation");
            $.validator.unobtrusive.parse($form);
},

The refreshValidator method is called when the DOM is ready on every page
load.

This seems like it was probably a hack to fix things because I'm doing
something wrong somewhere else.

Here's some example code:

*app-global.js*
https://www.dropbox.com/s/2z86kdbx9deswh2/shot_150129_111747.png?dl=0

*Auto.cshtml*
https://www.dropbox.com/s/r8x1izgtkei8h3a/shot_150129_111935.png?dl=0



Thanks,
Jason

**Comment by JaroslawWaliszko** [comment]
Your expression seems fine as well.

Looking at the screenshots I'm unable to point what is the origin of your issue. I may only guess that it is possibly related to some race conditions, mainly the script initializes before DOM is fully loaded. 

You can check if that problem is specific to expressive.annotations.js only or if it is more generic, related to jquery.validate.js as well. To verify it, just apply some other MVC built-in attributes to your model properties e.g. `[Required]`, `[Password]` etc, and check if that stuff also work occasionally or not. If there is an issue as well, it means your problem is not related to expressive.annotations.js explicitly.
