### ISSUE TITLE
Use with requirejs

### ISSUE THREAD

**Issue by HydrateEfficiently** [JaroslawWaliszko/ExpressiveAnnotations#48]
Hey Jaroslaw,

Thanks again for this awesome library. I'm using requireJS with my project (as a lot of others are) so I thought I'd let you know how to hook up the EA script with requireJS, and you can do whatever you may with that information.

First step is to alias all the paths for the scripts you need:
```javascript
requirejs.config({
    paths: {
        "jquery": "lib/jquery-1.8.2",
        "jquery-validate": "lib/jquery.validate",
        "jquery-validate.unobtrusive": "lib/jquery.validate.unobtrusive",
        "ea": "lib/expressive.annotations.validate"
    }
});
```

We also need to tell require what the various dependencies are:
1. JQuery validate depends on JQuery.
2. JQuery validate unobtrusive depends on JQuery, JQuery validate.
3. ExpressiveAnnotations depends on all of the above. We also need to tell require which variable to watch on the window so we can return the "ea" object when we load that script.
We can use "shim" to set all these requirements up:
```javascript
requirejs.config({
    shim: {
        "jquery-validate": ["jquery"],
        "jquery-validate.unobtrusive": ["jquery", "jquery-validate"],
        "ea":  { deps: ["jquery", "jquery-validate", "jquery-validate.unobtrusive"], exports: "ea" },
    }
});
```
Note: you should probably concatenate these two calls to requirejs.config.

Now, to load ExpressiveAnnotations you can simply include this line in your script:
```var ea = require("ea")```

**Comment by JaroslawWaliszko** [comment]
Hey, 
thank you for that information. I'm sure it will be helpful for some users.

I'll apply a *question* tag to this thread. Obviously, it is not a question, but sometimes people check *Issues* section in the hope of finding possible solutions to their problems, just by browsing through already solved ones. That's why it will be easier for them to filter out the *questions* out of the bag of other stuff like *bugs* etc.

Regards

**Comment by galvarez421** [comment]
I believe that the setup describe by @nth-commit will not work exactly right as of [jQuery Validation version 1.13.0](https://github.com/jquery-validation/jquery-validation/releases/tag/1.13.0), in which a [UMD wrapper](https://github.com/umdjs/umd) was added around the plugin code. To be clearer, the setup may not work reliably in optimized builds due to how RequireJS shims work. Per [RequireJS documentation on the shim config option](http://requirejs.org/docs/api.html#config):

> Only use other "shim" modules as dependencies for shimmed scripts, or AMD libraries that have no dependencies and call define() after they also create a global (like jQuery or lodash). Otherwise, if you use an AMD module as a dependency for a shim config module, after a build, that AMD module may not be evaluated until after the shimmed code in the build executes, and an error will occur. The ultimate fix is to upgrade all the shimmed code to have optional AMD define() calls.

 Since jQuery Validation is an AMD module with dependencies (jQuery) but is nonetheless being used as a shim dependency, after you build/optimize the modules, the Unobtrusive Validation and Expressive Annotations libraries won't necessarily wait for jQuery Validation to load, which would cause the described error. I have experienced this error in a project. I bypassed the error using the wrapShim build configuration option provided by RequireJS, but as the documentation states, this option is not guaranteed to work. So, I think in order to guarantee that this library works with RequireJS and other module loaders and bundlers that use AMD or CommonJS, it would probably be best to provide a UMD wrapper for this library.
