### ISSUE TITLE
"with" statement and strict mode

### ISSUE THREAD

**Issue by dannief** [JaroslawWaliszko/ExpressiveAnnotations#51]
Thanks for a great script. I've been using this in every asp.net MVC application since I discovered it.

I was recently facing a problem when I included this with another library that uses a global **use strict** statement. Due to the use of the **with** statement, the application was throwing errors in the console since the [**with** statement cannot be used in strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with)

I fixed the issue by modifying that other library to use strict mode only within the context of that script. But I thought I would call your attention to it, so that you might consider removing the deprecated keyword.

Thanks again.

**Comment by JaroslawWaliszko** [comment]
Hi,
Thanks. 

To be honest I know about the issue related to strict mode since the beginning. Nevertheless  `with` and `eval` keywords are essential, and I have no idea how to substitute them here. Their usage seems to be natural within the context of EA logic (evaluating expressions within the scope of model objects). If there are some ways to satisfy strict mode in this context (are they any?), I'll be more than happy to hear about them.

Regards

**Comment by dannief** [comment]
After looking at the code a bit, I understand the use of `with` and `eval`. One way, I suppose, to remove the dependency on `with` is to force the user to use a variable when creating expressions. e.g.

    (function(){
        "use strict";
          
        var model = {
            name: "Dannie",
        };
  
        eval("alert(model.name === 'Dannie')");
    })();

In C#

    [AssertThat("model.Name == 'Dannie'")]

Perhaps that `model` variable could be configurable. I understand that this would break backward compatibility though. So probably not worth the change.

A more drastic change solution may be to parse the expression for model property names and pre-pend the `model` variable before `eval`ing. I have to confess that I don't yet understand all the potential issues with using a `with` statement as described [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with). So again, I can't speak to whether it would be worth changing code that works.

**Comment by JaroslawWaliszko** [comment]
Hi,

the first idea, where the explicit change in each expression is required for the users to be done, is not what we'd like to do, as you've already noticed. The other way, to post-process the expressions, is much better. 

In the meantime, I've also come up with yet another idea and described it [on Stack Overflow](http://stackoverflow.com/questions/28877793/changing-the-execution-scope-of-eval-method-strict-mode-versus-with-statement) in details.

In short, in the places where `with` and `eval` are now used we can insert `ctxEval` substitute like this:
![image](https://cloud.githubusercontent.com/assets/1596462/6530514/d256a1fe-c431-11e4-9ed4-9873b39307b4.png)
where `ctxEval` is a method defined like below:
```
ctxEval: function (exp, ctx) { // evaluates expression in the scope of context object
    return (new Function('expression', 'context', 'with(context){return eval(expression)}'))(exp, ctx);
}
```
I've walked through [this blog post](http://www.2ality.com/2014/01/eval.html) and [this article](http://perfectionkills.com/global-eval-what-are-the-options/) before proposing that solution. I still don't know all pros and cons, so maybe someone will post his opinion at SO in some near future. If not, I think I'll go this way, because it seems to be simplest (although a bit hacky).

Finally, just short digression about switching to strict mode.

After reading [article about transitioning to strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode/Transitioning_to_strict_mode) I think it should be done gradually within the code you know. So the global `use strict;` pragma over all of the third-party scripts you've mentioned above, seems to be a bad idea whatsoever. Without comprehensive testing I wouldn't do that. It's because of some not obvious [strict JavaScript](http://ecma262-5.com/ELS5_HTML.htm#Section_4.2.2) behavior changes, which potentially may occur. What I mean by "not obvious" is not the explicit exceptions related to parse-time (like this related to `with` statement when the syntax error is immediately flushed to console) but hard to detect runtime errors, like that one ([see JSFiddle](https://jsfiddle.net/fw7n10ra/)):
```
var x = 7;
function strict(){
  'use strict';
  eval('var x = 12');
  console.log(x); // logs 7
}
strict();

var y = 7;
function sloppy(){
  eval('var y = 12');
  console.log(y); // logs 12
}
sloppy();
```

**Comment by JaroslawWaliszko** [comment]
Proposed solution pushed to master branch: https://github.com/JaroslawWaliszko/ExpressiveAnnotations/commit/73e0d606b53cb5144e49313a2c4a5b74c35cc90b
