### ISSUE TITLE
Custom c# type equivalent to "string" incorrectly parsed as "object" type on client side, fails deserialization during validation. How to force client side type to string?

### ISSUE THREAD

**Issue by theyetiman** [JaroslawWaliszko/ExpressiveAnnotations#65]
This is a little complex, but I have a custom type in c# called `StringEnum` which effectively is a `string`. I can see why EA detects its type as `object` on the client side, because it is not technically a `string` as far as the CLR is concerned. However, I have implicit operators which mean that I can treat it exactly the same as a `string` in c#, which means when it gets rendered out in my view using `@Model.Property` it just outputs a plain old `string`.

When EA tries to validate against it, it tries to do a JSON parse on the value, which fails because it is not in JSON notation as it's just a `string`.

Is there any way I can force EA to use `string` as the client side type so that validation will work?

**Comment by JaroslawWaliszko** [comment]
Hi, please provide sample code for that issue for me to reproduce it. I'm out of my laptop for couple of days so I cannot really help right now. As soon as I'll be next to the code I'll try to provide comprehensive answer. It can take max 2,5 week in worst case. Regards.

**Comment by theyetiman** [comment]
Hi Jaroslaw, thanks for your quick reply. Here's the implementation of `StringEnum`. It's an abstract class providing all the base functionality that needs to be implemented for each `StringEnum` instance (see `TravelType` below):

```c#
public abstract class StringEnum
	{
		public static bool operator ==(StringEnum a, StringEnum b)
		{
			// If both are null, or both are same instance, return true.
			if (System.Object.ReferenceEquals(a, b))
			{
				return true;
			}

			// If one is null, but not both, return false.
			if (((object)a == null) || ((object)b == null))
			{
				return false;
			}

			// Return true if the string values match:
			return a.Value == b.Value;
		}

		public static bool operator !=(StringEnum a, StringEnum b)
		{
			return !(a == b);
		}

		public static implicit operator String(StringEnum se)
		{
			return se == null ? null : se.Value;
		}		

		public static T Parse<T>(string s) where T : StringEnum
		{
			if (String.IsNullOrEmpty(s))
			{
				return default(T);
			}
			var props = typeof(T).GetProperties();
			var match = props.SingleOrDefault(p => !p.Name.Equals("Default", StringComparison.CurrentCultureIgnoreCase) && Convert.ChangeType(p.GetValue(null, null), typeof(T)).ToString().Equals(s, StringComparison.CurrentCultureIgnoreCase));
			if (match == null)
			{
				return default(T);
			}
			return (T)match.GetValue(null, null);
		}
		
		public StringEnum(string value)
		{
			Value = value;
		}

		private string Value { get; set; }

		public override string ToString()
		{
			return Value;
		}

		public override bool Equals(object obj)
		{
			try
			{
				return ((StringEnum)obj).Value == this.Value;
			}
			catch
			{
				return false;
			}
		}

		public override int GetHashCode()
		{
			return this.Value.GetHashCode();
		}

		public static IEnumerable<T> GetValues<T>() where T : StringEnum
		{
			return typeof(T).GetProperties().Select(p => (T)p.GetValue(typeof(T), new object[] { }));
		}
	}
```

And then an implementation of the abstract class:

```c#
public class TravelType : StringEnum
	{
		public TravelType(string value) : base(value) { }
		public static TravelType TailorMade { get { return new TravelType("Tailor-made"); } }
		public static TravelType GroupTour { get { return new TravelType("Group tour"); } }
		public static TravelType SelfOrganised { get { return new TravelType("Self-organised"); } }
	}
```

And then a model with a property of type `TravelType` and a property called `Destination` which has an EA RequiredIf attribute where the condition is based on the value of `TravelType`:

```c#
public class TravelPlanModel
	{
		public int Id { get; set; }

		[RequiredIf("TravelType != null", ErrorMessage = "Required if you've filled in Travel Type")]
		public string Destination { get; set; }	

		public TravelType TravelType { get; set; }
	}
```

Then just create a controller action which creates an empty `TravelPan` model and passes it to a view with `@Html.TextBoxFor(m => m.Destination)` and `@Html.TextBoxFor(m => m.TravelType)` and a validation message for `Destination`. That should be all that's required to reproduce, I hope!

Thanks again for your time and help, and I'd just like to say that I think the EA library is a brilliant and useful tool! Thanks for sharing.

**Comment by JaroslawWaliszko** [comment]
Hi. Thank you for detailed description. 

You probably also have custom model binder defined somewhere, since there is no out of the box conversion between `StringEnum` and `System.String`. Default model binder throws an exception if tries to deserialize form fields collection shipped in HTTP response into the model object using built-in converters.

When it comes to your direct problem, related to the client side of EA, the `parseObject` setting should be redefined in such case. This mechanism is most likely not widely used by the users, and probably its flexibility could be improved, but it is there if needed in emergency cases (more detiled discussion [here](https://github.com/JaroslawWaliszko/ExpressiveAnnotations/issues/38)). 

You should add the lines below into your scripts section:
```
<script>
    ea.settings.parseObject = function(value) {
        return value;
    }
</script> 
```
In short, that's all.

The reason is, when server-side returns type identified as `object`, client-side tries to handle that somehow, and assumes that input field value is given in json format. It is rather rare situation to have json in textbox, since form fields manually filled by the users are almost always represented by some simple types like `string` (textboxes), `boolean` (checkboxes), `numeric`, etc. Field content given in json is almost never written by hand. Nevertheless json is a format chosen for storing `object` type values because it seemed most natural and robust, and having the possibility of handling `object` types can be useful in many cases, e.g. when some data structure is provided by the server, i.e. see `EarlyYears` property in [sample project](https://github.com/JaroslawWaliszko/ExpressiveAnnotations/tree/master/src/ExpressiveAnnotations.MvcWebSample) and how it is handled (particularly take a look at [`IntArray.cshtml`](https://github.com/JaroslawWaliszko/ExpressiveAnnotations/blob/master/src/ExpressiveAnnotations.MvcWebSample/Views/Home/DisplayTemplates/IntArray.cshtml) template).

If you'd like to stay more compatible with default behavior, use this code below if you think you need that:
```
<script>
    ea.settings.parseObject = function(value) {
        try {
            return $.parseJSON(value);
        } catch (ex) {
            return value;
        }
    }
</script> 
```

Regards

**Comment by JaroslawWaliszko** [comment]
For next version I'm planning to modify the logic. It will be a breaking change. Instead of  `parseDate` and `parseObject` methods to be implemented, there will be only one method, mainly `parseValue` - to be overriden. In your case it could be used like this:
```
 ea.settings.parseValue = function(value, type, defaultParseCallback) {
	switch (type) {
		case 'traveltype':
			return value;
		default:
			return defaultParseCallback(value, type);
	}
}
```
I think it is self-descriptive. The advantage over current approach - parsing possibility will be given for any custom type (not only for `datetime` and *generic* `object` containing *all non-simple* types). I hope it will be more convenient (will it?).

**Comment by JaroslawWaliszko** [comment]
The idea has evolved, and finally changed once again. The planned modification in 2.6.0, in your case, instead of solution shown above, is going to be as follows:
 * at server-side decorate your property with special attribute which gives a hint to client-side, which parser should be chosen for corresponding DOM field value deserialization:
    ```
    class Model
    {
        [ValueParser('stringenum')]
        public TravelType TravelType { get; set; }
```

 * at client-side register such a parser:
    ```
    <script>
        ea.addValueParser('stringenum', function(value) 
            return value;
        });
```

Regards

**Comment by theyetiman** [comment]
This is a great idea. Thanks @JaroslawWaliszko I really appreciate your commitment to address this issue.
