### ISSUE TITLE
Inheritance security rules

### ISSUE THREAD

**Issue by pageroller** [JaroslawWaliszko/ExpressiveAnnotations#66]
Hey guys,

I'm getting a strange exception that only occurs in Production (Rackspace Cloud Sites Shared hosting) at the moment.

The exception is: 

Inheritance security rules violated while overriding member: 'ExpressiveAnnotations.Analysis.ParseErrorException.GetObjectData(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.

Does anyone have any idea on what to do?

**Comment by JaroslawWaliszko** [comment]
Hi, probably this is a bug. The potential explanation is here: http://stackoverflow.com/questions/3055792/inheritance-security-rules-violated-while-overriding-member-securityruleset-le. I'll try to solve this as soon as I'll get some free time, most likely next week. Regards.

**Comment by JaroslawWaliszko** [comment]
Hi, fix is pushed here: https://github.com/JaroslawWaliszko/ExpressiveAnnotations/commit/fbf8ba8b7505c8e22e61cfda3e74816e54d08c8c. It should work. If you have some time, try to compile it and check if the change is enough. If you wish I can also send you release version of that DLL (just to check, prior to publishing it to nuget, to be sure the bug is gone).

Regards

**Comment by JaroslawWaliszko** [comment]
I've decided to publish it. Give it a try.

**Comment by pageroller** [comment]
Works now, thanks.

**Comment by RodoxMan** [comment]
Hello guys!
I have the same error, can not solve it! Is there any other changes that you can fix this error?

**Comment by jwaliszko** [comment]
@RodoxMan: Which EA version are you using?

**Comment by RodoxMan** [comment]
I am using the latest version installed on NuGet, ie the version: 2.6.8

**Comment by jwaliszko** [comment]
@RodoxMan: Unfortunately I'm unable to provide a solution to this because I don't know what is the root of this problem. Maybe someone else is able to give any hint.

**Comment by RodoxMan** [comment]
Finally I managed to solve the problem! Added the statement: [assembly: Security Rules (SecurityRuleSet.Level1)] in ParseErrorException class. Now it's working.
Thank you so much!

**Comment by jwaliszko** [comment]
@RodoxMan: What I don't understand is that `GetObjectData` method [has](https://github.com/jwaliszko/ExpressiveAnnotations/blob/adc4c9ed72f6da26607ac6e372529ae5d4dea3f4/src/ExpressiveAnnotations/Analysis/ParseErrorException.cs#L42) `SecurityCritical` attribute applied to it, which says overridden member has the same security accessibility. Due to that changing the security rules shouldn't be required, as denoted in the post I [referenced above](http://stackoverflow.com/questions/3055792/inheritance-security-rules-violated-while-overriding-member-securityruleset-le). Currently, I have only basic knowledge related to .NET security, so maybe additional `SecurityPermission` attributes, applied [here](https://github.com/jwaliszko/ExpressiveAnnotations/blob/adc4c9ed72f6da26607ac6e372529ae5d4dea3f4/src/ExpressiveAnnotations/Analysis/ParseErrorException.cs#L30) and [here](https://github.com/jwaliszko/ExpressiveAnnotations/blob/adc4c9ed72f6da26607ac6e372529ae5d4dea3f4/src/ExpressiveAnnotations/Analysis/ParseErrorException.cs#L43), are redundant (and also CAS has been deprecated since .NET 4 as noted [here](http://stackoverflow.com/questions/10502750/securitypermission-in-a-serializable-method-in-c-sharp)). I've just removed those and compiled the code locally - [DLLs.zip](https://github.com/jwaliszko/ExpressiveAnnotations/files/185746/DLLs.zip). 

If you could remove your `[assembly: Security Rules (SecurityRuleSet.Level1)] ` attribute, and next reference these DLLs to check if the error is still there, I'd appreciate it. Also, if this doesn't help, it you find some time it would be nice to receive from your side small tiny sample where this error can be reproduced.

**Comment by RodoxMan** [comment]
Hello Sorry for the delay in response, I was absent due to my projects! Updated the dll is now working without the implementation of the [assembly: Security Rules (SecurityRuleSet.Level1)]

Thank you so much!
