### ISSUE TITLE
AssertThat on boolean checkbox field not working

### ISSUE THREAD

**Issue by sagiordano** [JaroslawWaliszko/ExpressiveAnnotations#69]
I'm not sure what I am trying to accomplish is possible.  I think I have the code right so maybe it is an issue of not having something setup correctly?

Anyway, I've got a check box.  If they check it, I want to return an error if another condition is met. I have a field called `Lead_Experimenter` and a field called `Lead_Experimenter_Count`.  If they check the `Lead_Experimenter` checkbox and the `Lead_Experimenter_Count` is greater than 0, it should return an error message.

Here is how I have it setup now:
```
[AssertThat("Lead_Experimenter == true && Lead_Experimenter_Count == 0", 
            ErrorMessage = " * there can only be one Lead Experimenter")]
public bool Lead_Experimenter { get; set; }
```
I feel like this is the correct logic but it is not firing.  I tried to test it by just making the checkbox required by doing the following:
```
[AssertThat("Lead_Experimenter == true", ErrorMessage = " * required")]
public bool Lead_Experimenter { get; set; }
```
But that is not firing either.  Any help would be appreciated.

Thanks!

**Comment by JaroslawWaliszko** [comment]
Hi,

Your code is correct. It should work. Is it client side or server side issue? If it is client side, when it is broken - when you click submit button or when you select/deselect checkbox without fiurther submission?

**Comment by sagiordano** [comment]
It is a client side issue.  Other client side validation is working ok but the expressive doesn't seem to fire at all.  Not when I check the checkbox or click submit.  I have 2 projects in my solution.  It is working fine in the other project but this is the first place I am trying to use it in this project so I'm thinking maybe something is not setup properly.  It looks to me that I have everything in place and it is the same as the other project but maybe I am missing something....but I'm also not getting an error.  The expressive syntax is recognized but its just not firing.

**Comment by JaroslawWaliszko** [comment]
Ok. It is weired. There must be [few steps accomplished](https://github.com/JaroslawWaliszko/ExpressiveAnnotations#what-about-the-support-of-aspnet-mvc-client-side-validation). Especially check the step 2 (are the validators wired up in Global.asax?) and 3 (is the expressive.annotations.validate.js script added to bundle below jquery validation files and finally available on your page?). 

Can you debug through that script? Try to put break-point here:

![image](https://cloud.githubusercontent.com/assets/1596462/8962278/1054e3d0-361a-11e5-905f-979ad2b95298.png)
and check if it is entering there when the submit button is clicked.

Also, aren't any errors displayed to console? Maybe try to setup your browser console to preserve the errors, e.g. in Chrome:

![image](https://cloud.githubusercontent.com/assets/1596462/8962560/8560df0c-361b-11e5-8ee8-6027389a51a8.png)

**The other issue is**, when validation is triggered when submit button is clicked, but **not** triggered when **only** checkbox (or radio) is clicked (without subsequent submit click). It is then related to [jquery.validate.js](http://jqueryvalidation.org/validate/) plugin and its setup (expressive annotations plugin relays on jquery validation one internally). One way to solve that issue is shown below (there are probably better ways):
```
<script>
    $('input[type="checkbox"], input[type="radio"]').on('change', function() {
        $(this).valid(); // triggers the validation test on change (jquery.validate.js does not trigger checkbox and radio validation on click, if such a click occurs prior to first submission attempt of entire form - later, validation is triggered 
    });                  // (downside of this hack - validation triggered 2 times for these fields after first form submission attempt is done)
</script>
```

**Comment by sagiordano** [comment]
Ahhhh! I forgot the registrations in the Global!

Thank you!
