### ISSUE TITLE
IsDateTime check?

### ISSUE THREAD

**Issue by konstrui** [JaroslawWaliszko/ExpressiveAnnotations#75]
Is there a IsDateTime or IsDate check for the AssertThat function?
I want to use this to check if the value is a date. The default attributes inside ASP MVC do not work.

**Comment by JaroslawWaliszko** [comment]
As you've most likely noticed, there is no such [built-in method](https://github.com/JaroslawWaliszko/ExpressiveAnnotations#built-in-functions) into EA. My thinking is, it would be too broad - there is too many standards (RFC2822, ISO 8601, RFC 1123, some country-specific, etc.). There is no "correct" format. It all depends on what various implementations consider as such. If any, better name would be e.g. `IsISODate()`. 

Nevertheless, for broad spectrum of formats, you can write such method by yourself, in the following manner:
```
class Model
{
    [AssertThat("IsDateTimeString(Date)")]
    public string Date { get; set; }

    public bool IsDateTimeString(string value)
    {
        DateTime temp;
        return DateTime.TryParse(value, out temp);
    }
```
```
<script>
    ea.adMethod("IsDateTimeString", function(value) {
        var millisec = Date.parse(value); 
        return typeof millisec === 'number' && !isNaN(millisec);
    });
```

Looking at the sample above, there is no guarantee though, that every input string which is parsed by JavsScript [`Date.parse(dateString)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) is parsed by .NET [`DateTime.Parse(string dateString)`](https://msdn.microsoft.com/en-us/library/vstudio/1k1skd40(v=vs.100).aspx) as well. Most likely not, because in remarks of both implementations (at MDN and MSDN) there is an information that input string, despite the fact being basically a string representing an ISO 8601 date, may accept also other formats, but with more or less unexpected parsing results.

If you want to be strict, and allow e.g. yyyy-mm-dd format only, you can write something like below:
```
class Model
{
    public bool IsDateTimeString(string value)
    {
        return Regex.IsMatch(value, @"^\d{4}-\d{2}-\d{2}$");
    }
```
```
<script>
    ea.adMethod("IsDateTimeString", function(value) {
        return /^\d{4}-\d{2}-\d{2}$/.test(value);
    });
```

**Comment by JaroslawWaliszko** [comment]
---
As a first supplementary information I'd like to add, that when (if) [async-work](https://github.com/JaroslawWaliszko/ExpressiveAnnotations/tree/async-work) branch  will be ready, there is a possibility to add [async](https://github.com/JaroslawWaliszko/ExpressiveAnnotations/tree/async-work#is-there-a-possibility-to-perform-asynchronous-validation) method for such checks, e.g.
```
ea.addAsyncMethod('IsDateTimeString', function(value, done) { 
    $.ajax({
        url: '/Controller/IsDateTimeString?input=' + value,
        success: function(result) {
            done(result);
        }
    });
});
```
It can be convenient, because actual format checking could be done at C# side only, no JavaScript related parsing logic would be needed. Such approach is less vulnerable for inconsistencies, which can occur at client-related server implementation and vice-versa, since only server one is really used. 

Actually such an option is already available at that branch, but it is not yet merged to master. Nevertheless you can still use it instead, if you wish.

---
As a second supplementary information I'd like to add, that in my above answer I've declared `Date` property as `string`. It is justified because we are checking string formats there. 

In some other cases, a property representing date and time, could be actually declared as `DateTime`. If so, it could be next used inside expressions, e.g. to compare dates which each other, e.g. `[AssertThat("Date > OtherDate")]`.

In such cases, you need to remember, that default type-detection logic provided out of the box by EA, parses `datetime` types using `Date.parse()` method at client-side. As already noted, `Date.parse()` accepts RFC2822 or ISO 8601 date strings. If input string is not compatible with these standards (e.g. yyyy-mm-dd), custom value parser needs to be provided, e.g.
```
class Model
{
    [AssertThat("Date > OtherDate")]
    [ValueParser("CustomDateParser")]
    public DateTime Date { get; set; }

    [ValueParser("CustomDateParser")]
    public DateTime OtherDate { get; set; }
```
```
ea.addValueParser('CustomDateParser', function(value) {	
    var arr = value.split('-');
    var date = new Date(arr[0], arr[1] - 1, arr[2]); // months are 0-based
    return date.getTime(); // return milliseconds
});
```

**Comment by konstrui** [comment]
Thanks for the information. Appreciate it!
