### ISSUE TITLE
Tokens in custom ErrorMessage or in ErrorMessageResourceName 

### ISSUE THREAD

**Issue by kevinneufeld** [JaroslawWaliszko/ExpressiveAnnotations#81]
```C#
[RequiredIf("IsService == true", ErrorMessage = "{0} is required because {1} has been checked" )]
[Display(ResourceType = typeof(Messages),Name = "FieldName_OtherName")]
public string OtherName {get; set;}

[Display(ResourceType = typeof(Messages),Name = "FieldName_IsService")]
public bool IsService {get; set;}
```
FieldName_OtherName = "Other Name"
FieldName_IsService = "Service Only"

Tokens: 
- {0} resolves to `Other Name` 
- {1} resolves to the expression: `IsService == true`
- {IsService} resolves to the value of **IsService** ==> `true`

What is the token for **IsService Name**,  `Service Only`?

**Comment by JaroslawWaliszko** [comment]
The `{0}` and `{1}` tokens handling is hardcoded internally:
```
public string FormatErrorMessage(string displayName, string expression)
{
    ....
    return string.Format(ErrorMessageString, displayName, expression);
```
The `{field}`, `{field.field}`, etc. tokens always extract the values of indicated fields (to prevent extraction, escape single bracket `{` (`}`) with corresponding doubled one `{{` (`}}`)).

Unfortunately, currently there is no implementation of any token which could be responsible for fields names extraction (so the name should be explicitly provided into the message, in your case: "{0} is required because Service Only has been checked").

While curly brackets are somehow analogical to .NET `string.Format` for values extraction, I haven't decided what token would be suitable for names extraction - I don't like `(field)` and `[field]` because `(` and `[` characters seems to be too common. If they are used for such a task, users will be enforced to escape them constantly when extraction is not desired. Maybe `<`? For the time being I dropped the idea of implementing this because I thought it is not that much needed. Nevertheless the idea is opened.

**Comment by JaroslawWaliszko** [comment]
To extract display names, no new format item is created, but current format specifier is extended to handle :n or :N suffixes (n indicator is case insensitive), i.e. `{field:n}`.

In your case `{IsService:n}` and `{IsService:N}` evaluates to *"Service Only"*.

Initial implementation pushed to master branch.

**Comment by kevinneufeld** [comment]
Thanks this is great help to us.

_____________________________
