### ISSUE TITLE
Mins sign generate exception during input

### ISSUE THREAD

**Issue by gennadiikurabko** [JaroslawWaliszko/ExpressiveAnnotations#83]
I have 2 input fields:
```razor
@Html.TextBoxFor(m => m.AmountFrom)
@Html.ValidationMessageFor(m => m.AmountFrom)

@Html.TextBoxFor(m => m.AmountTo)
@Html.ValidationMessageFor(m => m.AmountTo)
```
And model with next validation attributes:
```C#
[Range(-1000, 1000)]
[AssertThat("AmountTo == null || AmountFrom == null || AmountTo >= AmountFrom"]
public decimal? AmountFrom { get; set; }

[Range(-1000, 1000)]
[AssertThat("AmountTo == null || AmountFrom == null || AmountTo >= AmountFrom"]
public decimal? AmountTo { get; set; }
```
Now, to get exception you have to:
1. Enter 2 in the AmountFrom field
2. Start typing -1, and when you press '-' it throws error, as numeric parser of ASP.NET validation thinks it is okay, and then numeric parser of EA can't convert - sign to number.

I temporarly put try-catch in expressive.annotations.validate.js:
```javascript
$.validator.addMethod(method, function (value, element, params) {
    try
    {
        return computeAssertThat(value, element, params);
    }
    catch(e)
    {
        return false;
    }
}
```

And spent several hours trying to find good solution, but still have no idea what can be a good fix ...

**Comment by JaroslawWaliszko** [comment]
Thank you for pointing this problem out and for its comprehensive explanation.

I'm afraid there is no straightforward solution because such an error occurs when the value is not yet ready for being processed. Because this can happen as a direct result of the user action, it may be a good idea to only log an error to the console, but not re-throwing an exception further. It means that your modification is almost correct:


There are some solutions but they all seems to be overhead heavy for me, e.g.
 * usage of custom value parser and returning e.g. -1 in case the value format is not correct,
 * disable of field validation on keypress,
 * use drop-down control which contains proper numbers.

**Comment by JaroslawWaliszko** [comment]
I updated my comment. If you have any suggestions please share.
Regards

**Comment by JaroslawWaliszko** [comment]
Change pushed to master: https://github.com/JaroslawWaliszko/ExpressiveAnnotations/commit/e372988c5008d6c90cf055f1df2c4a8a5fef6d9e.

**Comment by gennadiikurabko** [comment]
Hey, thanks for such a fast fix. Actually my thoughts was somewhat similar, I tried to provide alternative numeric parser but that didn't went well. So, waiting for 2.6.4 in NuGet.
