### ISSUE TITLE
No more than 27 unique attributes of the same type can be applied for a single field or property

### ISSUE THREAD

**Issue by rwil02** [JaroslawWaliszko/ExpressiveAnnotations#85]
It must be me.
Got that same error, but this time with a list.

27 items in the list is OK, 30 (next I have without "hacking" an order) is not.

Which would imply that in some way it is "reusing" an ID somewhere?

@Html.TextBoxFor(m => m.ContainerNumber, null, (Model.ContainerId != 0 || Model.Locked) ? (object) new {disabled = "disabled", @class = "tickcheckbox"} : new {@class = "tickcheckbox", maxlength = 11})
            
[RequiredIf("Update || Deleted")]
public String ContainerNumber { get; set; }

This is the first field rendered that is not "hidden", and also the first field rendered that has an expressive annotation.

I'm going to dig and see if I can find anything more.

**Comment by JaroslawWaliszko** [comment]
Hi. I hope that despite these exceptions you are not going to dislike the number 27. Nevertheless, if the field has only one attribute applied to it, the occurrence of such an exception is rather alarming. I hope that at least the debugging process will be somehow smooth, because there are debugging symbols and sources pushed to SymbolSource.org. Due to that, now in any urgent cases you should be able to debug through the library with full source code support, when following [setup](http://www.symbolsource.org/Public/Home/VisualStudio) is defined in *Tools -> Debug -> Options* window:

![image](https://cloud.githubusercontent.com/assets/1596462/6217266/713d7532-b612-11e4-8227-a6625a4caf87.png)

![image](https://cloud.githubusercontent.com/assets/1596462/6217314/f9d4a06e-b612-11e4-801c-90716294c16b.png)

Regards

**Comment by rwil02** [comment]
Hmm, it's not triggering the PDB load, but that might be due to the exception:
System.InvalidOperationException occurred
Message: A first chance exception of type 'System.InvalidOperationException' occurred in 
System.Web.Mvc.dll

Additional information: No more than 27 unique attributes of the same type can be applied for a single field or property.

Which makes it look like System.Web.Mvc.dll

Or I might have an older version of your package:  2.2.7.0

Yeah, in which case I'll have to wait for our next release cycle to update.

**Comment by JaroslawWaliszko** [comment]
The PDB files are there, since the release of v2.4.3 version of the product. Version 2.2.7 is quite old. Despite the fact I do not remember any fixes related to this error-prone part of code since that time, it still will be best to switch to the latest release.

For my thinking and implementation details of the functionality related to multiple attributes handling in EA, I refer to this source (both question and answer): http://stackoverflow.com/q/25414296/270315.

Regards

**Comment by JaroslawWaliszko** [comment]
I'd like to provide some more help but, in order to do that, I need more details. It would be good if such details allow me to this reproduce this error (it would be even better if you could send me a tiny simplified project where this problem occurs).

**Comment by rwil02** [comment]
Thanks.
I've got to wait for the next release cycle to update (end of next week), once I've done that, if the problem persists I'll put together a minimal case for you.

**Comment by JaroslawWaliszko** [comment]
Thanks. Just bear in mind that switching from 2.2.7 to latest (2.6.4) is not completely painless. There are some, although very easy to fix, breaking changes. It depends how deeply you are exploiting this library. If this is just a basic usage, it should be only namespace fix. To be familiar with possible issues after the switch, the changelog can help: https://github.com/JaroslawWaliszko/ExpressiveAnnotations/releases.

**Comment by JaroslawWaliszko** [comment]
Hi, any more feedback on this? Has the latest version helped?

**Comment by rwil02** [comment]
They delayed the deployment a week, so rolling out tomorrow night, and a new version starting next week.

I'll let you know

**Comment by JaroslawWaliszko** [comment]
Hi. I assume the problem is expired for now, so I'm closing the issue. If any update appears please reopen it.
Regards.

**Comment by jwaliszko** [comment]
Source of error shown here: https://github.com/jwaliszko/ExpressiveAnnotations/issues/85.
