### ISSUE TITLE
ExpressiveAnnotations not validating on EditorFor cases.

### ISSUE THREAD

**Issue by mauriciojsola** [JaroslawWaliszko/ExpressiveAnnotations#88]
Hi Jaroslaw,

Not sure if I'm doing something wrong (would assume that yes :)).
I'm trying that a state/province to be selected if a country that require them is selected:

[RequiredIf("CountryCode == 'US' || CountryCode == 'CA' || CountryCode == 'AU' ", ErrorMessage = "State / Province is required")]
        public string StateProvinceAbbreviation{ get; set; }

public string CountryCode { get; set; }

Basically I'm using an EditorFor in a MVC partial view:

 @Html.EditorFor(m => m.PostalAddress, "_OrganizationPostalAddressPartial")

This is the html generated:

<select name="PostalAddress.CountryCode" id="PostalAddress_CountryCode" class="form-control js-countries-list ea-triggers-bound">

<select name="PostalAddress.StateProvinceAbbreviation" id="PostalAddress_StateProvinceAbbreviation" data-val-requiredif-fieldsmap="{&quot;CountryCode&quot;:&quot;string&quot;}" data-val-requiredif-expression="&quot;CountryCode == 'US' || CountryCode == 'CA' || CountryCode == 'AU' &quot;" data-val-requiredif-allowempty="false" data-val-requiredif="State / Province is required" data-val="true" class="form-control js-states-list ea-triggers-bound">

The question is: is this library able to validate correctly under the above circumstances?
If so, what I'm doing wrong? How can I make it to work correctly?

Thanks in advance! 

Mauricio

**Comment by JaroslawWaliszko** [comment]
Validation is probably not working because the partial view template *"_OrganizationPostalAddressPartial"* contains incorrect `input` field definition. Correct definition for your case should be similar to that below:

```
<input data-val="true"
       data-val-requiredif="State / Province is required."
       data-val-requiredif-allowempty="false"
       data-val-requiredif-expression="&quot;CountryCode=='US'||CountryCode=='CA'||CountryCode=='AU'&quot;"
       data-val-requiredif-fieldsmap="{&quot;CountryCode&quot;:&quot;string&quot;}"
       id="PostalAddress"
       name="PostalAddress"
       type="text"
       value="">
```

Notice the `data-val-*` html attributes. They are crucial for EA to be working, and are generated automatically when using the `@EditorFor()` helper method without template argument - check it yourself by using `@Html.EditorFor(m => m.PostalAddress)` instead.

Writing these attributes by hand is wrong solution for me. The point is they should be automatically re-generated when annotation changes. My advice is to get rid of custom templates for simple input fields.

**Comment by mauriciojsola** [comment]
Thanks for your quick answer Jaroslaw!
Sorry, I think I missed the HTML that was generated:

Custom template tag:
```
@Html.EditorFor(m => m.PostalAddress, "_OrganizationPostalAddressPartial")
```

HTML result:

```
<select name="PostalAddress.CountryCode" id="PostalAddress_CountryCode" class="form-control js-countries-list ea-triggers-bound">

<select name="PostalAddress.StateProvinceAbbreviation" id="PostalAddress_StateProvinceAbbreviation" data-val-requiredif-fieldsmap="{&quot;CountryCode&quot;:&quot;string&quot;}" data-val-requiredif-expression="&quot;CountryCode == 'US' || CountryCode == 'CA' || CountryCode == 'AU' &quot;" data-val-requiredif-allowempty="false" data-val-requiredif="State / Province is required" data-val="true" class="form-control js-states-list ea-triggers-bound">
```

I tried with simple input fields and it worked fine.
But... the idea of using custom templates is to avoid lots of boilerplate code spread all around.

For example, if you have a page that have a model that requires to have, for example, three different addresses, and lets suppose each address has 7 different fields, it is not a good idea to have 21 different fields to differentiate each address form. I think you get the idea :).

Maybe your library is not intended to cover all those cases, but I'm pretty sure that most of the people using custom templates would love you if you get support for custom templates. I have not seen any other library as extensible as this one.

Thanks for your help anyway. Your library is awesome!

Mauricio

**Comment by JaroslawWaliszko** [comment]
Your usage of editor templates should be modified - instead of providing name explicitly, write this:

`@Html.EditorFor(m => m.PostalAddress)`

and next, inside custom *"_OrganizationPostalAddressPartial"* template, which should be placed under *"EditorTemplates"* folder:
```
Views
    -> Shared
            -> EditorTemplates
                    -> _OrganizationPostalAddressPartial.cshtml
```
declare your model type:

`@model Namespace.PostalAddressType`

Your template will now be detected automatically for given type.

Then just use `EditorFor` helpers (or alternatives) in their standard form, e.g.:
```
@EditorFor(m => m.CountryCode)
@EditorFor(m => m.StateProvinceAbbreviation)
// or sth like: @DropDownListFor(m => m.StateProvinceAbbreviation, Model.Abbreviations)
// etc.
```

There will be no redundancy either, no boilerplate code and no hand-written html which will be generated. For more detailed examples go through the [sample project]( https://github.com/JaroslawWaliszko/ExpressiveAnnotations/tree/master/src/ExpressiveAnnotations.MvcWebSample).

Regards.
